"""
Django settings for bestglobeshop project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l10%=h+#zj!5*_iik6wvs7a_wfps3l#us+19-@-2+wfwzbvguh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['117.242.151.204','103.93.102.200','127.0.0.1', 'bestglobeshop.com', 'localhost', 'www.bestglobeshop.com', '192.168.2.204', '192.168.2.105', '192.168.75.128', '113.21.72.5']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
    'cart',
    'api',
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'corsheaders',

]



LOGOUT_REDIRECT_URL = '/admin/login/'


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.IsAdminUser',
        'rest_framework.permissions.AllowAny',
    ],

}

CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    'https://bestglobeshop.com','http://bestglobeshop.com', 'https://www.bestglobeshop.com','http://www.bestglobeshop.com'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://bestglobeshop.com",
    "http://www.bestglobeshop.com",
    "http://localhost:3000",
    
]

CART_SESSION_ID = 'cart'
ROOT_URLCONF = 'bestglobeshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processor.cart_total_amount',
            ],
        },
    },
]

WSGI_APPLICATION = 'bestglobeshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DEFAULT_DARK_MODE = False

# MongoDB connection string 

# DATABASES = {
#         'default': {
#             'ENGINE': 'djongo',
#             'NAME': 'bestglobeshop',
#             'CLIENT': {
#                 'host': 'mongodb+srv://bestglobeshop:best9531707495@cluster0.1mhmjks.mongodb.net/?retryWrites=true&w=majority',
#                 'username': 'bestglobeshop',
#                 'password': 'best9531707495',
#             }  
#         }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'bestglobeshop',
#         'CLIENT': {
#             'host': 'mongodb://root:ShuvoDip@192.168.2.105:27017/?authMechanism=DEFAULT',
#             'username': 'root',
#             'password': 'ShuvoDip',
#         }
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'bestglobeshop',
#         'USER': 'postgres',
#         'PASSWORD': 'ShuvoDipDuoples8918945997',
#         'HOST': '192.168.2.105',     # Or your PostgreSQL database's host IP address
#         'PORT': '5432',  # Leave empty for default PostgreSQL port (5432)
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets/'),
]


import mimetypes
mimetypes.add_type("text/css", ".css", True)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SMTP Server settings 
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST = 'mail.duoples.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'contact@bestglobeshop.com'
EMAIL_HOST_PASSWORD = 'Bestglobe@95besty'
DEFAULT_FROM_EMAIL = 'Bestglobeshop Contact <contact@bestglobeshop.com>'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# LOGIN_REDIRECT_URL = 'index'
# LOGOUT_REDIRECT_URL ='index'
PASSWORD_RESET_TIMEOUT_DAYS = 1

STATIC_URL = '/static/'
STATIC_ROOT = './static_files/'

DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_ENDPOINT = 's3storage.duoples.com'
MINIO_STORAGE_ACCESS_KEY = 'ecDSpGgudXurFDei5sPN'
MINIO_STORAGE_SECRET_KEY = 'gWqKogjJlksxPUd3dqgRvy8SuA3aNY40yvoDuiVW'
MINIO_STORAGE_USE_HTTPS = False
MINIO_STORAGE_MEDIA_OBJECT_METADATA = {"Cache-Control": "max-age=1000"}
MINIO_STORAGE_MEDIA_BUCKET_NAME = 'local-media'
MINIO_STORAGE_MEDIA_BACKUP_BUCKET = 'Recycle Bin'
MINIO_STORAGE_MEDIA_BACKUP_FORMAT = '%c/'
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_STATIC_BUCKET_NAME = 'local-static'
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
