# Generated by Django 4.2.11 on 2024-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cart_price_alter_cart_total_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
