# Generated by Django 4.2.11 on 2024-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userprofile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mode_preference',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
