# Generated by Django 4.1.13 on 2024-05-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cart_id_alter_cart_price_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
