# Generated by Django 4.1.13 on 2024-05-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
