# Generated by Django 5.0.6 on 2024-05-28 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
