# Generated by Django 5.0.6 on 2024-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_payment_razorpay_order_id_payment_razorpay_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
