# Generated by Django 5.0.6 on 2024-06-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_cartitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
